name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt black==24.10.0 mypy pandas-stubs types-requests pyarrow-stubs types-html5lib lxml-stubs scipy-stubs
      - name: mypy
        run: mypy ./CandleNet/
      - name: black (check)
        run: black --check ./CandleNet/