name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Cache venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Set up venv
        if: steps.cache.outputs.cache-hit != 'true'
        run: python -m venv .venv

      - name: Install uv
        run: pipx install uv

      - name: Install deps
        run: |
          source .venv/bin/activate
          python -m pip install --upgrade pip
          uv pip install -r requirements.txt black==24.10.0 mypy pandas-stubs types-requests pyarrow-stubs types-html5lib lxml-stubs scipy-stubs types-seaborn types-PyYAML      

      - name: mypy
        run: |
          source .venv/bin/activate
          mypy ./CandleNet/

      - name: black (check)
        run: |
          source .venv/bin/activate
          black --check ./CandleNet/


  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Cache venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Set up venv
        if: steps.cache.outputs.cache-hit != 'true'
        run: python -m venv .venv

      - name: Install uv
        run: pipx install uv

      - name: Install Dependencies
        run: |
          source .venv/bin/activate
          pip install --upgrade pip
          uv pip install -r requirements.txt

      - name: Run CI Tests
        run: |
          source .venv/bin/activate
          PYTHONPATH=. pytest ./tests/ --maxfail=5 -k "not web_access and not slow"
